# This will run on Travis' 'new' container-based infrastructure
sudo: false 

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - "./miniconda.sh -b"
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda

install:
    - conda install --yes sphinx

# Blacklist
branches:
  only:
    - ufs_public_release
    - ufs_public_release_v0

# Environment variables
env:
  global:
    - GH_REPO_NAME: stochastic_physics
    - DOXYFILE: $TRAVIS_BUILD_DIR/
    - GH_REPO_REF: github.com/pjpegion/stochastic_physics.git

# Build your code e.g. by calling make
script:
    - pushd docs
#   Use Sphinx to make the html docs
    - make html
#   Tell GitHub not to use jekyll to compile the docs
    - touch build/html/.nojekyll
    - popd

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/build/html
  github_token: $GH_REPO_TOKEN
  on:
    tags: true
